### ISSUE TITLE
HEC is not working whenever app generate more events

### ISSUE THREAD

**Issue by sureshreddygovindu** [splunk/splunk-library-javalogging#127]
Team, 

I'm using HEC for ingest logs to splunk from cloudfoundy.  each app is coded in the spring boot(1.5), I'm using logback-spring.xml. this app usually generates 1000 events/second. I've observed that below things
1. CPU usage 
2. Memory consumption 
3. No threads internally.  

 app crashes due to above issues. can you suggest us, can I do any settings to do ?

**Comment by sachinsharma9393** [comment]
same issue, with 1.5.3 , tried 1.7.1,.2,.3
also  with 1.8.0
![Screenshot from 2020-05-26 21-26-39](https://user-images.githubusercontent.com/13165013/82922769-a7a97480-9f97-11ea-9720-8e85ab644b0a.png)

**Comment by bparmar-splunk** [comment]
Hi @sureshreddygovindu,
Since we did not get any update from you.

We are closing this issue for now by assuming it as resolved based on above [comment](https://github.com/splunk/splunk-library-javalogging/issues/127#issuecomment-1180348302).

Please let us know, if you still face such issue.

Thank you.
