### ISSUE TITLE
Got high CPU usage and Memory Consuming after run the application

### ISSUE THREAD

**Issue by naksri379** [splunk/splunk-library-javalogging#128]
My application got high CPU usage and memory consuming after I ran the application with log to splunk in a moment.

I try to find a root cause by creating a new simple endpoint ( print log and return 200 ) then call it many times to see heap size
![4](https://user-images.githubusercontent.com/18605247/62914591-14fa6900-bdbb-11e9-99c2-d870645bec13.png)
I found out that heap size tends to grow up continuously and event I stop calling that endpoint 
the heap size still not drop.

I use Eclipse Memory Analyzer tool to detect what cause of consuming high memory. And this is the results.
![1](https://user-images.githubusercontent.com/18605247/62914865-58a1a280-bdbc-11e9-98a2-361157a9c554.png)
(Client Connection Manager create LinkedList many times.)

This is my logback and simple endpoint
![2](https://user-images.githubusercontent.com/18605247/62914922-9ef70180-bdbc-11e9-9b53-111488ad4f2c.png)

![3](https://user-images.githubusercontent.com/18605247/62914935-ad451d80-bdbc-11e9-8dea-765eac933539.png)

**Comment by naksri379** [comment]
Is this possible be the root cause?
https://issues.apache.org/jira/browse/HTTPASYNC-94

"the default settings of maxConnection (20) and maxConnectionPerRoute (2). After setting those configs to higher numbers, the problem was solved."

**Comment by naksri379** [comment]
I've attached my simple project with jmeter config in zip file in order to replicate a problem.
[test-splunk.zip](https://github.com/splunk/splunk-library-javalogging/files/3495572/test-splunk.zip)

**Comment by sureshreddygovindu** [comment]
@naksri379 
I'm facing same issue  whenever I put some load(Jmeter) on the application. our splunk HEC is load balanced with 16 servers. I don't think issue with HEC endpoint in my case.  can you please resolve and suggest what should we do in this case? 

1. Is there a way to increase threads or parallelism ?
2. If I generate 1000 log events for sec, how can log appender works in this case?

**Comment by sureshreddygovindu** [comment]
@splunk-srv-dev-platform 
can you suggest on this issue?

**Comment by shakeelmohamed** [comment]
A quick investigation based on the Jira ticket linked by @naksri379, the issue seems to be in how the http client is built in `HttpEventCollectorSender::startHttpClient()` https://github.com/splunk/splunk-library-javalogging/blob/master/src/main/java/com/splunk/logging/HttpEventCollectorSender.java.

A potential fix would include:
* setting a higher value than 1 or 0 for `setMaxConnTotal()` - need to determine what value is actually used when 0 is passed in.
* setting a higher value than the default 2 by using `setMaxConnPerRoute()`

**Comment by bparmar-splunk** [comment]
Hi @naksri379,
We have made few changes (in [v1.11.5](https://github.com/splunk/splunk-library-javalogging/releases/tag/1.11.5)) related to timeout settings and also upgraded its okhttp library to version [4.9.3](https://square.github.io/okhttp/changelogs/changelog_4x/#version-493) (Vulnerability [CVE-2021-0341](https://nvd.nist.gov/vuln/detail/CVE-2021-0341) was fixed in v4.9.2).

Please re-validate your use case and let us know, if you still face any issue.

**Comment by bparmar-splunk** [comment]
Hi @naksri379,
Since we did not receive any updates from you.
We assume that the issue has been resolved based on above [comment](https://github.com/splunk/splunk-library-javalogging/issues/128#issuecomment-1210387211).

We are closing this issue for now.
Please let us know in case of further queries.

Thank you !
