### ISSUE TITLE
Replacing the CloseableHttpAsyncClient with a shared OkHttpClient is still causing huge memory usage

### ISSUE THREAD

**Issue by czirjak** [splunk/splunk-library-javalogging#162]
Reference PR: https://github.com/splunk/splunk-library-javalogging/pull/135

We use the version of 1.8 and we still face the same issue what is describe in the referenced PR.
The situation is the same with CloseableHttpAsyncClient and OkHttpClient too.

That is all what we have in our logback.xml (Java 8, SpringBoot, Tomcat)

`    <appender name="SPLUNK" class="com.splunk.logging.HttpEventCollectorLogbackAppender">
        <url>XYZ</url>
        <token>XYZ</token>
        <index>XYZ</index>
        <source>XYZ</source>
        <sourcetype>XYZ</sourcetype>
        <host>XYZ</host>
        <messageFormat>json</messageFormat>
        <disableCertificateValidation>true</disableCertificateValidation>
        <middleware>HttpEventCollectorMiddleware</middleware>
        <layout class="ch.qos.logback.classic.PatternLayout">
            <pattern>
                %msg
            </pattern>
        </layout>
    </appender>`

It burns the entire heap up in some minutes.

**Comment by zeldigas** [comment]
The problem is related to the fact that this appender does not control the flow in any way at all. Current implementation just assumes that it can push as many events without any kind of "backpressure" as it can, that results in OOM - right now there is no way ready-to-use option to monitor the queue or controll it - appender just keep putting requests in http client's queue (see OkHttpClient dispatcher) and so far I don't see an easy way to stop.

This makes current implementation completely broken for schenarios with high spikes of log events or when some logs are fine to loose (that is easily achieved in other loggers by wrapping real logger in async one and configuring queue options there).

**Comment by bparmar-splunk** [comment]
Hi @czirjak,
We have made few changes (in [v1.11.5](https://github.com/splunk/splunk-library-javalogging/releases/tag/1.11.5)) related to timeout settings and also upgraded its okhttp library to version [4.9.3](https://square.github.io/okhttp/changelogs/changelog_4x/#version-493) (Vulnerability [CVE-2021-0341](https://nvd.nist.gov/vuln/detail/CVE-2021-0341) was fixed in v4.9.2).

Please re-validate your use case and let us know, if you still face any issue.

**Comment by bparmar-splunk** [comment]
Hi @czirjak,
We assume that the issue might have been resolved based on above [comment](https://github.com/splunk/splunk-library-javalogging/issues/162#issuecomment-1178882935). 
We are closing this ticket for now.

Please let us know in case of any further queries.
Thank you.
