### ISSUE TITLE
spring-boot / spring-cloud-sleuth / logback / splunk-library-javalogging

### ISSUE THREAD

**Issue by thpeter** [splunk/splunk-library-javalogging#69]
Hi, 
when building a webapp with the above mentioned stack my app will get stuck during startup. 

When I remove sleuth/zipkin it will start again (so I guess it has something to do with the HttpClient instrumentation done by sleuth) 
I could also work around the problem by configuring the batch_size_count to 1 (looks like the spring startup is somehow blocked while waiting for the batchsize to be reached)

A minimal example application is attached

[logtest.zip](https://github.com/splunk/splunk-library-javalogging/files/1939020/logtest.zip)

**Comment by shakeelmohamed** [comment]
Thanks for the report @thpeter

**Comment by martinvisser** [comment]
With version 1.8.0 this still happens, using Spring Boot 2.3, Spring Cloud Hoxton.

**Comment by bparmar-splunk** [comment]
Hi @thpeter and @martinvisser,

Thank you for bringing this up !

Since v1.9.0, HttpClient is replaced with OkHttp library in Splunk Java logging. And currently we have latest version as **1.11.5**.
We recommend you to update your library to current version ([1.11.5](https://github.com/splunk/splunk-library-javalogging/releases/tag/1.11.5)) and re-validate your use-case.

Please let us know if you still face any issue.
Thank you !

**Comment by martinvisser** [comment]
Sorry, I can't re-validate this anymore, because I'm no longer working with projects that use this.

**Comment by bparmar-splunk** [comment]
@martinvisser,
Thank you for your response.

Closing this issue.
