### ISSUE TITLE
Conflict in name of appender plugin : HttpEventCollectorLog4jAppender.java uses same plugin  name as org.apache.logging.log4j.core.appender.HttpAppender 

### ISSUE THREAD

**Issue by swapvai** [splunk/splunk-library-javalogging#80]
Team,

When I am using Http Appender with com.splunk.logging package with log4j2, it was giving me below warning.

WARN StatusLogger Plugin [http] is already mapped to class org.apache.logging.log4j.core.appender.HttpAppender, ignoring class com.splunk.logging.HttpEventCollectorLog4jAppender

After looking at code I found @Plugin(name = "Http" has same name as used with org.apache.logging.log4j and that was taking precedence over com.splunk.logging.

For workaround I renamed plugin name in HttpEventCollectorLog4jAppender.java and rebuild it in my local environment and it worked.

Ideally we should have unique name for custom appenders to avoid conflicts with org.apache.logging.log4j. 

If we publish new version with unique plugin name it will be very helpful for all.

Thanks for such helpful custom appender.

Version of this project you're using (ex: 1.6.0)
Platform version (ex: Windows 10)
Framework version (ex: Java 8)
Splunk version (cloud)

-Swapnil

**Comment by shakeelmohamed** [comment]
Hi @swapvai,

This issue makes sense, however resolving it would be a breaking change.
Feel free to send us a PR if you're interested in moving this along.

**Comment by luisrguzmanjr** [comment]
I was curious how this is progressing?  I have run into the same issue and I am trying to implement this solution for my organization, but I am not able to send messages to our splunk since the com.splunk.logging http appender is being overridden:

DEBUG Building Plugin[name=appender, class=**org.apache.logging.log4j.core.appender.HttpAppender**].
DEBUG HttpAppender$Builder(url="%scheme%://%host%:%port%", method="null", connectTimeoutMillis="null", readTimeoutMillis="null", ={}, SslConfiguration=null, verifyHostname="null", ignoreExceptions="null", PatternLayout([%d{MM/dd/yyyy HH:mm:ss}] [%-5p] [%c{3}] - %m%n), name="splunkhec", Configuration(MyApp), Filter=null)
**ERROR Http contains invalid attributes "disableCertificateValidation", "index", "source", "class", "token"**

**Comment by luisrguzmanjr** [comment]
I was curious how this is progressing?  I have run into the same issue and I am trying to implement this solution for my organization, but I am not able to send messages to our splunk since the com.splunk.logging http appender is being overridden:

DEBUG Building Plugin[name=appender, class=**org.apache.logging.log4j.core.appender.HttpAppender**].
DEBUG HttpAppender$Builder(url="%scheme%://%host%:%port%", method="null", connectTimeoutMillis="null", readTimeoutMillis="null", ={}, SslConfiguration=null, verifyHostname="null", ignoreExceptions="null", PatternLayout([%d{MM/dd/yyyy HH:mm:ss}] [%-5p] [%c{3}] - %m%n), name="splunkhec", Configuration(MyApp), Filter=null)
**ERROR Http contains invalid attributes "disableCertificateValidation", "index", "source", "token"**

-Lou

**Comment by ronosaurus** [comment]
Would this satisfy backwards compatibility and get around the plugin naming issue?

```java
// existing
public class HttpEventCollectorLog4jAppender extends AbstractAppender

// backwards compatibility
@Plugin(name = "Http", category = "Core", elementType = "appender", printObject = true)
@SuppressWarnings("serial")
public final class HttpEventCollectorLog4jAppender2 extends HttpEventCollectorLog4jAppender

// plugin renamed to avoid conflicts with HttpAppender
@Plugin(name = "SplunkHttp", category = "Core", elementType = "appender", printObject = true)
@SuppressWarnings("serial")
public final class SplunkHttpEventCollectorLog4jAppender extends HttpEventCollectorLog4jAppender
```

3 copies of constructor and PluginFactory stuff but only one implementation

**Comment by tdhellmann** [comment]
Sorry for the delayed communication - we've just merged a fix for this to develop as: https://github.com/splunk/splunk-library-javalogging/pull/92/files
